### ISSUE TITLE
We should have a PR review protocol

### ISSUE THREAD

**Issue by NewJerseyStyle** [NewJerseyStyle/polis#108]
**What would you like documented?**
We should have a shared PR review protocol so peer can cross review based on the shared protocol.

**Where should it live?**
[GitHub wiki page](https://github.com/CivicTechTO/polis/wiki/) create a new page for PR review

**Any additional context which might be relevant?**
Zin and Patcon have done few PR reviews.
We are lack of standard protocol of how to review and what are the criteria for PR reviews.

**Comment by NewJerseyStyle** [comment]
@thomassth Do you have any good references that can help us on this?
@Zen-cronic @patcon Any advice?

**Comment by thomassth** [comment]
Usually I'd think "passing CI tests" & "doing whatever it's trying to solve (& don't break other stuff in the process)" are the 2 main goals

Goal #1 is easy enough I think, even though sometimes we'd need exceptions, but that'd be case by case

For goal #2, someone other than the submitting person should (best case) spin up an instance with the new code & check if it's doing what it says. Some sort of auto deploy test build might be possible, or even a storybook deploy can be enough if it's localized UI changes.

Or if we want efficiency, "looks good to me" can be a way, provided there's trust in the submitting person & the reviewer knows what they're doing.

**Comment by patcon** [comment]
I like what @thomassth said.

**Comment by NewJerseyStyle** [comment]
So basically if it passes E2E test then we assume it is safe to merge?

Few weeks ago we met a question with PR from Vinesh where he added some comments to improve the readability of the code. Then format of code/comment the only thing changed... I don't know if it is a thing to our repository 🤔

**Comment by Zen-cronic** [comment]
great points from @thomassth 
In the same thread, if we're gonna be relying on passing ci tests as our primary criteria, then it wouldn't hurt to increase our e2e test coverage (and possibly add unit tests where needed). 

In terms of code change, as long as there's no significant changes without thorough explanation, we could safely assume the author of the PR is in the best interest of the project. 

edit: how much is "significant changes" is still up to interpretation.  for me, a good rule of thumb is a couple hundred lines in diff.

**Comment by NewJerseyStyle** [comment]
Sounds good, we can start from this set of assumptions and improve them in progress (if it isn't broke don't fix it)

I will compile them into a wiki page as a reference before closing the issue
