### ISSUE TITLE
Investigate and Update Cypress E2E Test

### ISSUE THREAD

**Issue by NewJerseyStyle** [NewJerseyStyle/polis#31]
**Description:**

The Cypress E2E test GitHub Action currently set up for testing the web server's UIs appears to be outdated and hasn't been maintained for some time.  We need to determine its current functionality and identify any necessary updates.

**Tasks:**

* **Verify Functionality:** Run the existing Cypress E2E tests to confirm whether they are still passing and accurately reflect the current UI state.  Document any failures or unexpected behavior.
* **Assess Test Coverage:** Evaluate the existing test suite for completeness.  Are all critical UI elements and user flows adequately covered?  Identify any missing tests, particularly focusing on areas that could benefit from additional verification, such as keyboard shortcuts.
* **Update Tests (if necessary):**  Based on the findings from the previous steps, update the Cypress tests to address any failures, improve coverage, and incorporate tests for missing functionality (e.g., keyboard shortcuts).
* **Documentation:** Update the documentation to reflect any changes made to the tests and their coverage.

**Expected Outcome:**

A functional and up-to-date Cypress E2E test suite that provides comprehensive coverage of the web server's UI, including keyboard shortcuts and other essential user interactions.  The GitHub Action should be reliable and consistently reflect the current state of the application.

**Priority:**  Medium (Investigate and update as soon as possible to ensure test reliability)

**Comment by ballPointPenguin** [comment]
FYI I recently updated the github action for e2e tests in the compdem repo https://github.com/compdemocracy/polis/blob/edge/.github/workflows/cypress-tests.yml
and they are generally running and passing.
Coverage could be expanded, and libraries updated for certain.
Robust API request specs would be ⭐

**Comment by Zen-cronic** [comment]
Here are my findings:

> **Tasks:**
> 
>    Verify Functionality: Run the existing Cypress E2E tests to confirm whether they are still passing and accurately reflect the current UI state.  Document any failures or unexpected behavior.

All the current e2e tests pass.

> 
>    Assess Test Coverage: Evaluate the existing test suite for completeness.  Are all critical UI elements and user flows adequately covered?  Identify any missing tests, particularly focusing on areas that could benefit from additional verification, such as keyboard shortcuts.

Keyboard shortcuts are not implemented. 

> 
>    Update Tests (if necessary):  Based on the findings from the previous steps, update the Cypress tests to address any failures, improve coverage, and incorporate tests for missing functionality (e.g., keyboard shortcuts).
> 

We could use the `@cypress/code-coverage` plugin to test coverage. 

>    Documentation: Update the documentation to reflect any changes made to the tests and their coverage.
>

No changes made so far.

The GitHub Action flow in this branch is already the exact same as @ballPointPenguin has updated. 

Summary: we could use the cypress coverage plugin and implement keyboard shortcuts if that feature is a top-priority.

**Comment by NewJerseyStyle** [comment]
About the feature request of testing keyboard shortcuts, it is for testing pull request #3 . However as you may notice we are pausing all PR to check our branches and decide which branch should we use for development, the implementation may not be a top-priority.

**Comment by Zen-cronic** [comment]
Gotcha. So, i believe we'll follow this path: 

1. decide on the dev branch
2. merge the keyboard shortcuts pr - we should have this feature as part of our accessibility revamp (https://developer.mozilla.org/en-US/docs/Web/Accessibility/Keyboard-navigable_JavaScript_widgets)
3. after merge, write cypress tests for the shortcuts

**Comment by NewJerseyStyle** [comment]
Good, I will assign you on the PR after decision of dev branch, feel free to read our discussion on PR32 where we discovered the issue of the branches (a rename operation was done without announcement so we did some merge and edit on wrong branch we are trying to revert it now)
