### ISSUE TITLE
E2E test failed for `edge-civictechto` after merging #32

### ISSUE THREAD

**Issue by NewJerseyStyle** [NewJerseyStyle/polis#39]
**Expected behavior**:
E2E passes while merging #37

**Actual behavior**:
E2E test failed, the cause seem to be #32 merged before fixing github action script branch name issue

**To Reproduce**:
[Please check E2E test](https://github.com/CivicTechTO/polis/actions/runs/11410788293/job/31753787441?pr=38)

❌ client-participation/embeds.cy.js
❌ client-admin/conversation.cy.js

**Comment by NewJerseyStyle** [comment]
@Zen-cronic please provide assistant to @thomassth if he need help in identifying problem

**Comment by Zen-cronic** [comment]
I just reviewed both failures in #32 after rerunning the ci with logs. More details there.
