### ISSUE TITLE
Remove last two commits from `edge`

### ISSUE THREAD

**Issue by patcon** [NewJerseyStyle/polis#50]
May I do this? I think they're just there from our own merge of my feature branch, but they're also upstream, and will allow us to sync `edge` (and start making PRs based from it). But I'll need to force-push to remove history :(

Maybe I could accompany the change with instructions for everyone on how to delete the local branch and side-step any scary warnings, and then it's alright?

## Commits in question

<img width="1386" alt="Screenshot 2024-10-21 at 12 53 05 PM" src="https://github.com/user-attachments/assets/a01cd873-e625-45e1-8e41-147038a908fb">

**Comment by NewJerseyStyle** [comment]
Gooooooooooooooo! 🥅

**Comment by patcon** [comment]
Done! thanks :)

**Comment by patcon** [comment]
I also locked the branch, so it's read-only and can only be sychronized with upstream (I'm going to create an issue to do this automatically)
