### ISSUE TITLE
[a11y] Issue 7: Incorrect ARIA role for form element (Participation Page)

### ISSUE THREAD

**Issue by NewJerseyStyle** [NewJerseyStyle/polis#65]
**Description:**

The participation page uses an ARIA role of "form" on a `<form>` element, which is redundant and can cause accessibility issues. The `<form>` element already has an implicit "form" role.  Using unnecessary ARIA roles can interfere with assistive technologies.

**Steps to Reproduce:**

1. Navigate to the participation page (e.g. `https://pol.is/4cvkai2ctw`)
2. Inspect the `<form>` element using a browser's developer tools.

**Expected Behavior:**

The `<form>` element should not have an explicit ARIA role="form" attribute.

**Actual Behavior:**

The `<form>` element has an unnecessary ARIA role="form" attribute.

**Component/Area:** Participation page

**Source:** Auto evaluation

**Affected Elements:** form

**Comment by thomassth** [comment]
Should be fixed with https://github.com/CivicTechTO/polis/pull/32
