### ISSUE TITLE
[a11y] Issue 10: Incorrect use of paragraph elements for spacing (Participation Page)

### ISSUE THREAD

**Issue by NewJerseyStyle** [NewJerseyStyle/polis#68]
**Description:**

Paragraph elements (`<p>`) are being misused for creating spacing on the participation page instead of using CSS. This is semantically incorrect and can confuse assistive technologies.

**Steps to Reproduce:**

1. Navigate to the participation page (e.g. `https://pol.is/4cvkai2ctw`)
2. Inspect the HTML source code.

**Expected Behavior:**

Use CSS for spacing; do not use `<p>` elements for this purpose.

**Actual Behavior:**

`<p>` elements are misused for spacing.

**Component/Area:** Participation page

**Source:** Other

**Affected Elements:** p

**Comment by thomassth** [comment]
Dev notes: 
- This issue only exist when there are content in description.
- Likely related to incorrect handlebar conditions setup
